name: Trivy Scan Dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.45.1/trivy_0.45.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.45.1_Linux-64bit.deb

      # Step 3: Scan `testpackage.json` for vulnerabilities
      - name: Scan `testpackage.json` for vulnerabilities
        run: |
         trivy fs --exit-code 1 --severity LOW,MEDIUM,HIGH,CRITICAL --ignore-unfixed vulnerability-scan/testpackage.json

